# supooted time units: seconds, minutes, hours, days, months
auth:
  nonce_size: 12
  access_token_duration:
    minutes: 360
  refresh_token_duration:
    months: 1
  token_purge_interval:
    hours: 1
verify:
  email_verification_code_duration:
    days: 5
  email_ver_purge_interval:
    days: 1
  password_reset_code_duration:
    hours: 1
  password_reset_purge_interval:
    days: 1

# Database connection pool configuration
database:
  connection_pool:
    min_size: 2
    max_size: 10
    max_queries: 50000
    max_inactive_connection_lifetime: 300
    timeout: 60
    command_timeout: 60
    statement_cache_size: 100

# Image handling configuration
picture:
  max_size: "5 * 1024 * 1024"  # 5MB
  chunk_size: "512 * 1024"     # 512KB
  max_width: 1920
  max_height: 1080
  min_width: 100
  min_height: 100
  allowed_types:
    - image/jpeg
    - image/png
    - image/avif
    - image/webp
  avif_quality: 70  # Quality setting for AVIF conversion (0-100)

openai:
  base_url: null  # Optional: for Azure OpenAI or custom endpoints
  model: "gpt-4.1-mini"  # Language model that supports image generation tool
  # max_retries: 3 # not used yet
  # timeout: 120  # not used yet

  # Image generation tool configuration
  image_generation:
    size: "1024x1024"
    quality: "low"  # low, medium, high, auto
    format: "jpeg"  # png, jpeg, webp
    background: "transparent"  # opaque, transparent, auto