# supooted time units: seconds, minutes, hours, days, months
auth:
  nonce_size: 12
  access_token_duration:
    minutes: 15
  refresh_token_duration:
    months: 1
  token_purge_interval:
    hours: 1
verify:
  email_verification_code_duration:
    days: 5
  email_ver_purge_interval:
    days: 1
  password_reset_code_duration:
    hours: 1
  password_reset_purge_interval:
    days: 1
