services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network

  api:
    build:
      context: .
      args:
        - DEBUG=${DEBUG} # Custom DEBUG flag
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG} # Custom DEBUG flag
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT} # Application port
      # - ${DEBUG_PORT}:${DEBUG_PORT} # Debug port if debugging
      - 5678:5678 # hardcoding this cause i cant pass it for some reason
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
