version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  api:
    build: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PORT=${PORT} # Application port
      - HOST=${HOST} # Host for the application
      - DEBUG=${DEBUG} # Custom DEBUG flag
      - DEBUG_PORT=${DEBUG_PORT} # Debug port if debugging
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
      - 5678:5678
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
