name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Navigate to Backend directory and build Docker image
      working-directory: ./Backend
      env:
        MODE: ${{ secrets.MODE }}
        PORT: ${{ secrets.PORT }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        VERSION: ${{ secrets.VERSION }}
      run: docker compose build