name: Backend CI/CD

on:
  push:
    branches:
      - main
      - test_github_actions
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Navigate to Backend directory and build Docker image
      working-directory: ./Backend
      env:
        MODE: ${{ secrets.MODE }}
        PORT: ${{ secrets.PORT }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        VERSION: ${{ secrets.VERSION }}
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest .

    -name: Run tests inside the Docker container
      run: |
        docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest
