name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - test_github_actions
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Navigate to Frontend directory and build Docker image
      working-directory: ./website
      env:
        NODE_ENV: production
        PORT: ${{ secrets.FRONTEND_PORT }}
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
