name: Python CI

on:
  push:
    branches:
      - main
      - test_github_actions
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./Backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run unit tests
      working-directory: ./Backend
      env:
        MODE: ${{ secrets.MODE }}
        PORT: ${{ secrets.PORT }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        VERSION: ${{ secrets.VERSION }}
        DEBUG_PORT: ${{ secrets.DEBUG_PORT }}
        MAIL_SSL: ${{ secrets.MAIL_SSL }}
        MAIL_TLS: ${{ secrets.MAIL_TLS }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      run: |
        python -m unittest discover -s tests -p "test_*.py"
